#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: generic
sudo: false

git:
  depth: 1

env:
  global:
    - BYOND_MAJOR="511"
    - BYOND_MINOR="1385"
    - BYOND_MACRO_COUNT=4
  matrix:
    - DM_MAPFILE="cyberiad"
    - DM_MAPFILE="metastation"
    - DM_MAPFILE="test_all_maps"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh
script:
  - (num=$(grep -Ern '\\(red|blue|green|black|italic|bold|b|i[^mc])' code/ | wc -l); echo "$num BYOND text macros (expecting ${BYOND_MACRO_COUNT} or fewer)"; [ $num -le ${BYOND_MACRO_COUNT} ])
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} paradise.dme


# File checks - Rules:
# - No step_x/step_y in .dmm files
# - html/changelog/example.yml untouched
# - Changelog generation works
matrix:
  include:
    - env: FILE_CHECKS=1
      addons:
      install:
        - pip install --user PyYaml -q
        - pip install --user beautifulsoup4 -q
      before_script:
      script:
        - shopt -s globstar
        - (! grep 'step_[xy]' _maps/map_files/**/*.dmm)
        - md5sum -c - <<< "6dc1b6bf583f3bd4176b6df494caa5f1 *html/changelogs/example.yml"
        - python tools/ss13_genchangelog.py html/changelog.html html/changelogs

# NodeJS Checks
# - Builds NanoUI
    - env: NODEJS_CHECKS=1
      language: node_js
      node_js:
        - "9"
      addons:
      before_install:
        - npm install -g bower gulp
        - cd ./nano/
      install:
        - npm install --loglevel=error
        - bower install --silent
      before_script:
      script:
        - gulp --min